var $home=$(".home, .menu_list.home"),$profile=$(".profile, .menu_list.profile"),
$archive=$(".archive, .menu_list.archive"),$cl=$(".is-clone");
function firstLook(){$(".home_listitem").children(".home_imglist:first").addClass("active"),
$(".home_listtextholder:first").children(".home_listtextselect").addClass("active"),
$(".home_titlecontainer:first").children(".home_titlewrapper").addClass("active")}
$(function(){$(".home_listitem").clone().appendTo(".home_listwrapper").addClass("is-clone");$(".home_container").show(),$(".home_pagetitle.horizontal, .profile_pagetitle.vertical, .archive_pagetitle.vertical").addClass("active"),
$(".home_pagetitle.vertical, .profile_pagetitle.horizontal, .archive_pagetitle.horizontal").removeClass("active"),
$(".profile_container, .archive_container").hide(),$(".mobile_listitem").children(".mobile_imglist:first").addClass("active"),
$(".mobile_listselectholder:first").children(".mobile_listselect").addClass("active"),"https://www.ondrejzunka.com/#la-fleur"==$(location).attr("href")?($("input[name=Category][value='la-fleur']").click(),$cl.hide(),setTimeout(function(){firstLook()},1e3))
:"https://www.ondrejzunka.com/#ai"==$(location).attr("href")?($("input[name=Category][value='ai']").click(),$cl.hide(),setTimeout(function(){firstLook()},1e3)):"https://www.ondrejzunka.com/#other"==$(location).attr("href")?($("input[name=Category][value='other']").click(),$cl.hide(),setTimeout(function(){firstLook()},1e3))
:"https://www.ondrejzunka.com/#outside"==$(location).attr("href")?($("input[name=Category][value='Outside']").click(),$cl.hide(),setTimeout(function(){firstLook()},1e3)):"https://www.ondrejzunka.com/#superrare"==$(location).attr("href")?($("input[name=Category][value='superrare']").click(),$cl.hide(),setTimeout(function(){firstLook()},1e3)):($cl.show(),firstLook())});
var tl=gsap.timeline({paused:!0});$home.click(function(){const e=$(".main_inner.home");e.hasClass("is--open")||($archive.removeClass("is--open"),$profile.removeClass("is--open"),$(".home_container").show(),
$(".profile_container, .archive_container").hide(),e.addClass("is--open"),$(".home_pagetitle.horizontal").hasClass("active")||($(".home_pagetitle.horizontal, .profile_pagetitle.vertical, .archive_pagetitle.vertical").addClass("active"),$(".home_pagetitle.vertical, .profile_pagetitle.horizontal, .archive_pagetitle.horizontal").removeClass("active")))}),
$profile.click(function(){const e=$(".main_inner.profile");e.hasClass("is--open")||($archive.removeClass("is--open"),$home.removeClass("is--open"),$(".profile_container").css({display:"flex"}),
$(".home_container, .archive_container").hide(),e.addClass("is--open"),$(".profile_pagetitle.horizontal").hasClass("active")||($(".profile_pagetitle.horizontal, .home_pagetitle.vertical, .archive_pagetitle.vertical").addClass("active"),$(".profile_pagetitle.vertical, .home_pagetitle.horizontal, .archive_pagetitle.horizontal").removeClass("active")))}),
$archive.click(function(){const e=$(".main_inner.archive");e.hasClass("is--open")||(tl.restart(),$home.removeClass("is--open"),$profile.removeClass("is--open"),$(".archive_container").show(),
$(".profile_container, .home_container").hide(),e.addClass("is--open"),tl.to(".archive_imgitem",{delay:.5,opacity:1,duration:.5,stagger:{ease:"power2.easeOut",from:"edges",each:.05}}),tl.play(),
$(".archive_pagetitle.horizontal").hasClass("active")||($(".archive_pagetitle.horizontal, .profile_pagetitle.vertical, .home_pagetitle.vertical").addClass("active"),$(".archive_pagetitle.vertical, .profile_pagetitle.horizontal, .home_pagetitle.horizontal").removeClass("active")))}),
$(".menu_list").click(function(){$(".menu_navbar").click()}),$(".archive_linkblock").on("mouseover",function(e){var t=document.getElementById("archive");$(".archive_previewimg").css({top:Math.random()*t.clientHeight/1.5+"px",left:Math.random()*t.clientWidth/1.25+"px"})}),$(".home_listitem").hover(hoverOrClick),$(".mobile_listitem").click(mobileClick),
$(function(){$(".home_filterlabel").click(function(){const e=$(this).prev();$(".home_listitem").children(".home_imglist").removeClass("active"),$(".home_listitem").children(".home_listtextholder").children(".home_listtextselect").removeClass("active"),$(".home_listitem").children(".home_titlecontainer").children(".home_titlewrapper").removeClass("active"),"All"==e.val()?setTimeout(function(){$cl.show(),
$(".home_listitem:first").children(".home_imglist").toggleClass("active"),$(".home_listitem:first").children(".home_listtextholder").children(".home_listtextselect").toggleClass("active"),$(".home_listitem:first").children(".home_titlecontainer").children(".home_titlewrapper").toggleClass("active")},500):($cl.hide(),setTimeout(function(){$(".home_listitem:first").children(".home_imglist").toggleClass("active"),
$(".home_listitem:first").children(".home_listtextholder").children(".home_listtextselect").toggleClass("active"),$(".home_listitem:first").children(".home_titlecontainer").children(".home_titlewrapper").toggleClass("active")},500)),window.history.pushState("page","",$(this).attr("data-link"))})}),
$("html, body").on("wheel",function(e){$(".home_listwrapper").scrollTop($(".home_listwrapper").scrollTop()-e.originalEvent.wheelDeltaY)});
var doc=window.document,context=doc.querySelector(".home_listwrapper"),clones=context.querySelectorAll(".is-clone"),disableScroll=!1,scrollHeight=0,scrollPos=0,clonesHeight=0,i=0;function getScrollPos(){return(context.pageYOffset||context.scrollTop)-(context.clientTop||0)}function setScrollPos(e){context.scrollTop=e}function getClonesHeight(){for(clonesHeight=0,i=0;i<clones.length;i+=1)clonesHeight+=clones[i].offsetHeight;return clonesHeight}function reCalc(){scrollPos=getScrollPos(),scrollHeight=context.scrollHeight,clonesHeight=getClonesHeight(),scrollPos<=0&&setScrollPos(1)}function scrollUpdate(){disableScroll||(scrollPos=getScrollPos(),clonesHeight+scrollPos>=scrollHeight?(setScrollPos(1),disableScroll=!0):scrollPos<=0&&(setScrollPos(scrollHeight-clonesHeight),disableScroll=!0)),disableScroll&&window.setTimeout(function(){disableScroll=!1},55)}function init(){reCalc(),context.addEventListener("scroll",function(){window.requestAnimationFrame(scrollUpdate)},!1),window.addEventListener("resize",function(){window.requestAnimationFrame(reCalc)},!1)}"loading"!==document.readyState?init():doc.addEventListener("DOMContentLoaded",init,!1);
